# Definiciones de puertos y constantes DHCP
CLIENT_PORT = 68
SERVER_PORT = 67
BROADCAST_MAC = "ff:ff:ff:ff:ff:ff"
BROADCAST_IP = "255.255.255.255"
ZERO_IP = "0.0.0.0"

# Opciones DHCP (RFC 2132)
OPT_MESSAGE_TYPE = 53
OPT_SERVER_ID = 54
OPT_PARAM_REQ_LIST = 55
OPT_CLIENT_ID = 61

# Tipos de Mensajes DHCP
DHCP_DISCOVER = 1
DHCP_OFFER = 2
DHCP_REQUEST = 3
DHCP_DECLINE = 4
DHCP_ACK = 5
DHCP_NAK = 6
DHCP_RELEASE = 7
DHCP_INFORM = 8
